---
DISABLE_LINTERS:
  - SPELL_CSPELL
ENABLE:
  - ANSIBLE
  - PYTHON
APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
ANSIBLE_DIRECTORY: .
ANSIBLE_ROLES_PATH: roles
ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
