---
DISABLE_LINTERS:
  - SPELL_CSPELL
# ENABLE: ANSIBLE
#   - PYTHON
#   - YAML
APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - YAML_YAMLLINT
  - PYTHON_PYLINT
ANSIBLE_DIRECTORY: .
