---
DISABLE_LINTERS:
  - SPELL_CSPELL
ENABLE:
   - ANSIBLE
   - PYTHON
   - YAML
APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
ANSIBLE_DIRECTORY: .
ANSIBLE_ROLES_PATH: roles
ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
