---
- name: Playbook update_brew.yml
  hosts: localhost
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      ansible.builtin.stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      ansible.builtin.fail:
        msg: Homebrew is missing, install from http://brew.sh
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Install Homebrew
      ansible.builtin.command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
  roles:
    - update
  vars:
    ansible_connection: local
