name: ansible-lint

on:
  push:
    branches-ignore:
      - master

  workflow_dispatch:
  
jobs:
  build:
    name: Ansible Lint
    runs-on: macos-12
    steps:
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
