---
name: CI-check

on:
  push:
    branches-ignore:
      - master

  workflow_dispatch:

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base with MegaLinter
        uses: oxsecurity/megalinter/flavors/cupcake@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}