---
name: MegaLinter

on: # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - main

  workflow_dispatch:

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base with MegaLinter
        uses: oxsecurity/megalinter/flavors/python@vbeta
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
